---
name: Text-MediawikiFormat
version: !!perl/hash:Module::Build::Version
  original: 0.04
  version:
    - 0
    - 40
author: []
abstract: Translate Wiki markup into other text formats
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: 1.14
  URI::Escape: ''
build_requires:
  Test::More: 0.3
provides:
  Text::MediawikiFormat:
    file: lib/Text/MediawikiFormat.pm
    version: 0.04
  Text::MediawikiFormat::Block:
    file: lib/Text/MediawikiFormat/Blocks.pm
  Text::MediawikiFormat::Blocks:
    file: lib/Text/MediawikiFormat/Blocks.pm
generated_by: Module::Build version 0.2804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
