---
name: Text-MediawikiFormat
version: !!perl/hash:Module::Build::Version
  original: 0.01
  version:
    - 0
    - 10
author:
  - |-
    chromatic, C<chromatic@wgz.org>, with much input from the Jellybean team
    (including Jonathan Paulett).  Kate L Pugh has also provided several patches,
    many failing tests, and is usually the driving force behind new features and
    releases.  If you think this module is worth buying me a beer, she deserves at
    least half of it.
abstract: |-
  html-aware module for translating Wiki formatted text
                          into other formats
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: 1.14
  URI::Escape: ''
build_requires:
  Test::More: 0.3
provides:
  Text::MediawikiFormat:
    file: lib/Text/MediawikiFormat.pm
    version: 0.01
  Text::MediawikiFormat::Block:
    file: lib/Text/MediawikiFormat/Blocks.pm
  Text::MediawikiFormat::Blocks:
    file: lib/Text/MediawikiFormat/Blocks.pm
generated_by: Module::Build version 0.2804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
